duti -s com.apple.automator.editorOpen org.golang.go-script editor
duti -s com.apple.automator.editorOpen public.plain-text editor
duti -s com.apple.automator.editorOpen public.shell-script editor
duti -s com.apple.automator.editorOpen public.data editor
duti -s com.apple.automator.editorOpen public.make-source editor
duti -s com.apple.automator.editorOpen public.python-script editor
duti -s com.apple.automator.editorOpen .lua editor
duti -s com.apple.automator.editorOpen .txt editor
duti -s com.apple.automator.editorOpen .sh editor
duti -s com.apple.automator.editorOpen .json editor
duti -s com.apple.automator.editorOpen .yaml editor
duti -s com.apple.automator.editorOpen .toml editor
duti -s com.apple.automator.editorOpen .cpp editor
duti -s com.apple.automator.editorOpen .js editor
duti -s com.apple.automator.editorOpen .java editor
duti -s com.apple.automator.editorOpen .rb editor
duti -s com.apple.automator.editorOpen .css editor
duti -s com.apple.automator.editorOpen .vim editor
duti -s com.apple.automator.editorOpen .xml editor
duti -s com.apple.automator.editorOpen .c editor
duti -s com.apple.automator.editorOpen .h editor
duti -s com.apple.automator.editorOpen .py editor
